# -*- coding: utf-8 -*-
"""Minutes Meeting generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lHHNzGdUpdbERDbcfuSFLpdh72nRBOB
"""

# ==================================
# Meeting Minutes Generator
# ==================================
import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR \n")

#User Inputs
meeting_title = input("Enter meeting title: ")
date = input("Enter meeting date (YYYY-MM-DD): ")
time = input("Enter meeting time : ")
participants = input("Enter participants (Comma separated) : ")
agenda = input("Enter agenda points (Comma separated) : ")
decisions = input("Enter decisions taken (Comma separated) : ")
action_items = input("Enter action items (Comma separated) : ")
prepared_by = input("prepared by: ")

#Process INputs
participants_list = [p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",") if d.strip]
action_list = [a.strip() for a in action_items.split(",") if a.strip()]


#Creating structured meeting minutes
minutes = {
    "Meeting Title": meeting_title,
    "Date": date,
    "Time": time,
    "participants": ",".join(participants_list),
    "Agenda": ",".join(agenda_list),
    "Decisions": ",".join(decisions_list),
    "Action Items": ",".join(action_list),
    "Prepared By": prepared_by,
    "Generated on": datetime.now().strftime("%Y-%m-%d %H:%M:%S")

}

#Create to DataFrame
df = pd.DataFrame(list(minutes.items()), columns = ["Field","Details"])

print("\n Meeting Minutes Generated Successfully \n")
display(df)

#Save as csv
df.to_csv("meeting minutes.csv",index=False)
print("\n File saved as meeting_minutes.csv")