# -*- coding: utf-8 -*-
"""Sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBTa_0eQIta34L-y4zJeNt1RiOwKHXx8
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util

#load the model
model=SentenceTransformer('all-MiniLM-L6-v2')
#take input from user
text1=input("Enter text 1 : ")
text2=input("Enter text 2 : ")
# convert text to embeddings
embedding1 =model.encode(text1)
embedding2 =model.encode(text2)
#calculate similarity
similarity = util.cos_sim(embedding1,embedding2)
#show result
print("\n Similarity score",round(float(similarity),2))
if similarity >0.75:
  print("similarity level : High")
elif similarity >0.4:
  print("similarity level : Medium")
else:
  print("similarity level : Low")